---

- import_tasks: ssh.yml
  tags: 
    - server_security
    - server_security_ssh

- import_tasks: fail2ban.yml
  when: server_security_enable_fail2ban
  tags: 
    - server_security
    - server_security_fail2ban